### PR TITLE
[RED-659] Add Aviary.yaml

### PR DESCRIPTION
**Pull request by infosec-wf**
This is an automated pull request to migrate existing Raven config files to the new aviary.yaml file in individual repos. This PR requires infosec approval prior to merging. Please do not close this PR or merge it prior to this approval.

Please reach out in the "Infosec Forum" HipChat room with any questions.

@infosec-wf, @dustinhiatt-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 1
* Watched file ```aviary.yaml``` added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by matthewlorimor-wf** [comment]
Security +1

**Comment by matthewlorimor-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
+1

**Pull request merged**
