### PR TITLE
Skiplist compare

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
CODE REVIEW

In order to make this package more generic (keys other than uint64) I modified the interfaces a bit so all they require is the Compare method.  This means you could use skip lists to store strings, ints, uints, and random type but also kills us performance-wise.  I would love generics here as the "byposition" and "byvalue" code shows that we are taking a 5x performance hit to make this code generic.  I also killed the skiplist* type as it requires computable keys which only works if the key is computable (number types basically).  We could re-introduce this with generics, if we ever get them.

@alexandercampbell-wf @beaulyddon-wf @tannermiller-wf @ericolson-wf @stevenosborne-wf @tylertreat-wf @rosshendrickson-wf

### CODE REVIEW

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by beaulyddon-wf** [comment]
But why would you ever need generics? ;p

+1

**Comment by tannermiller-wf** [comment]
+1 Time to rewrite in a different language :wink:

**Comment by alexandercampbell-wf** [comment]
I got Go code to call Rust code a few days ago. It's actually not too difficult-- just compile Rust to a C library (easier than you think) and write headers so Go can recognize it.

**Comment by tannermiller-wf** [comment]
@alexandercampbell-wf yeah I was playing with that in december. It's pretty smooth actually.

**Comment by alexandercampbell-wf** [comment]
The biggest problem is that you're constantly casting your variables back and forth between `Rust -> C -> Go` and `Go -> C -> Rust`. Very awkward.

**Comment by tannermiller-wf** [comment]
Yeah, that sucks, but it's a small price to pay.

**Pull request merged**
