### PR TITLE
Add an explicit timer and stop it

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
Time.After() will create a goroutine that won't get GC'd until the timer is triggered.  Really long timeouts therefore will cause slow memory leaks.  Here we manually stop the timer if someone triggers the completion channel, thereby aiding GC.

@Workiva/dtbackend

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by matthinrichsen-wf** [comment]
+1

**Comment by blakewilson-wf** [comment]
+1

**Comment by seanstrickland-wf** [comment]
+1

**Comment by rmconsole-wf** [comment]
QA review can be found here: https://jira.atl.workiva.net/browse/RM-16142

**Pull request merged**
