### PR TITLE
Add Offer method to RingBuffer

### PR DESCRIPTION
**Pull request by tylertreat-wf**
This adds an Offer method to the RingBuffer which returns false when
trying to put to a full queue.

@dustinhiatt-wf @alexandercampbell-wf @stevenosborne-wf @brianshannan-wf

### CODE REVIEW

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Comment by tylertreat-wf** [comment]
Failed build fixed with https://github.com/Workiva/go-datastructures/pull/93

**Pull request merged**
