### PR TITLE
B link concurrency

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
I'm still testing with this, and I still think there is a race condition outside of threadsafety that the authors didn't address to my knowledge, that being how to deal with the root node and what happens when a new root should appear in your stack.  I'm guessing they tested with a low number of threads and high node width because that is actually a serious problem.  I could find the time to fix this up but the initial performance numbers indicate you are better off single threaded due to lock contention.  More of an academic PR now as I don't think the authors had really done the work they needed to do to make this work.  The only solution I can think of off the top of my head is to maintain a parent pointer as well so you could always find your way to the new root (there may have been several new roots since you found your insertion node) or restart the insertion pessimistically, which is very problematic in its own right.  I think Intel may have the right idea with this: http://cs.unc.edu/~sewall/palm.pdf.  I think avoiding contention altogether is the best solution.

@alexandercampbell-wf @beaulyddon-wf @tylertreat-wf @ericolson-wf @rosshendrickson-wf @stevenosborne-wf @tannermiller-wf

### CODE REVIEW

**Comment by alexandercampbell-wf** [comment]
Accidentally checked in `.prof` file, and it looks like there are some debug logs still present.

Otherwise, +1

**Comment by beaulyddon-wf** [comment]
+1

**Comment by tannermiller-wf** [comment]
+1

**Comment by rosshendrickson-wf** [comment]
+1

**Pull request merged**
