### PR TITLE
future/selectable: lazy allocate wait chan

### PR DESCRIPTION
**Pull request by funny-falcon**
Before:
BenchmarkSelectable-4   	 1000000	      1085 ns/op
BenchmarkSelectable 	 2000000	       983 ns/op
After:
BenchmarkSelectable-4   	 2000000	       991 ns/op
BenchmarkSelectable 	 2000000	       885 ns/op

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by rmconsole-wf** [comment]
QA review can be found here: https://jira.atl.workiva.net/browse/RM-16341

**Comment by funny-falcon** [comment]
Can't log in to your jira :-(

**Pull request merged**
