### PR TITLE
Remove duplicate values

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
This PR does two things:
1) Removes redundant information that was on the nodes and instead relies on calling interval methods.  This reduces performance and memory consumption and means there is less state to track.
2) Kills the insert method.  All intervals are assumed to be immutable.  To insert, the consumer should query for all affected ranges, delete them, mutate them, and re-insert them.  This will also more closely mimic how this operation would be performed in an R-Tree.

@alexandercampbell-wf @rosshendrickson-wf @ericolson-wf @seanstrickland-wf @matthinrichsen-wf @wesleybalvanz-wf @blakewilson-wf

### CODE REVIEW

**Comment by dustinhiatt-wf** [comment]
CI is fixed with: https://github.com/Workiva/go-datastructures/pull/119

**Comment by alexandercampbell-wf** [comment]
+1, I really like this change

**Comment by johnryan-wf** [comment]
+1

**Comment by alexandercampbell-wf** [comment]
@dustinhiatt-wf ready to merge

**Pull request merged**
