### PR TITLE
augmentedtree: add traverse func

### PR DESCRIPTION
**Pull request by azr**
Hello there !

A need I had :)

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by alexandercampbell-wf** [comment]
Would you mind adding a unit test covering `Traverse()`?

**Comment by azr** [comment]
Not at all :)

**Comment by azr** [comment]
is it okay like this ? LGTM :)

**Comment by azr** [comment]
?

**Comment by alexandercampbell-wf** [comment]
@azr sorry about the delay. Thanks for the contribution! Looks good to me.

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by azr** [comment]
Hey no problem :D

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by rmconsole-wf** [comment]
QA review can be found here: https://jira.atl.workiva.net/browse/RM-15648

**Pull request merged**
