### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by tylertreat-wf**
Add Travis CI.

@alexandercampbell-wf @dustinhiatt-wf @stevenosborne-wf

### CODE REVIEW

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by alexandercampbell-wf** [comment]
+1

Nice! Thank you @tylertreat-wf!

**Comment by alexandercampbell-wf** [comment]
Closes https://github.com/Workiva/go-datastructures/issues/66

**Comment by tylertreat-wf** [comment]
Welp, https://travis-ci.org/Workiva/go-datastructures/jobs/68482154

**Comment by dustinhiatt-wf** [comment]
@tylertreat-wf The stretchr guys modified testify awhile back :/.  assert.Equal(0, int32(0)) is now false.

**Comment by tylertreat-wf** [comment]
@alexandercampbell-wf @dustinhiatt-wf Weeee, build fixed.

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
+1

**Pull request merged**
