### PR TITLE
RM-25125 Fix #183

### LINKED ISSUE #183: Get from PriorityQueue
This snippet of code gives me:
```
func main() {
	myqueue := queue.NewPriorityQueue(20, true)
	myqueue.Put(Myfloat(4))
	myqueue.Put(Myfloat(-1))
	myqueue.Put(Myfloat(-99))
	myqueue.Put(Myfloat(104))

	result, _ := myqueue.Get(3)
	fmt.Println(result)
}
```
`[-99 -1]`

While I expected `[-99 -1 4]`

Why did it happen? 

P.S Compare method for `Item` interface.
```
type Myfloat float32

func (mi Myfloat) Compare(other queue.Item) int {
	omi := other.(Myfloat)
	if mi > omi {
		return 1
	} else if mi == omi {
		return 0
	}
	return -1
}
```

### PR DESCRIPTION
**Pull request by andreis**
```
pq.Get(x)
```
where `pq` is a priority queue and `x` is equal or greater than `pq.Len()` returns only `pq.Len()/2` elements.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1 You'll need to pull in master to get the build to pass

**Comment by brianshannan-wf** [comment]
+1

**Pull request merged**
