### PR TITLE
Patch Panic on Augmented Interval Tree Traverse

### PR DESCRIPTION
**Pull request by matthinrichsen-wf**
Attempting to Traverse and empty interval tree causes a panic.

@dustinhiatt-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by travissmith-wf** [comment]
+1

**Comment by teresarevious-wf** [comment]
RM +1

 verified dependencies

**Pull request merged**
