### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by nikai3d**

### CODE REVIEW

**Comment by alexandercampbell-wf** [comment]
+1, thank you

**Comment by alexandercampbell-wf** [comment]
@dustinhiatt-wf

**Comment by alexandercampbell-wf** [comment]
It looks like Travis is failing because of a race condition somewhere in `trie/ctrie`. Interesting stack trace, but it can't be related to this PR.

IMO this is safe to merge.

**Comment by tylertreat-wf** [comment]
+1

**Pull request merged**
