### PR TITLE
Update testify failures

### PR DESCRIPTION
**Pull request by alexandercampbell-wf**
### Code Review

Testify (our testing framework) made some breaking changes and tests were showing failures of the form

```go
0x0 != 0
0x7 != 7
0x5 != 5
```

and so on. This was caused by a type mismatch: `int64 != int` and so on. Fix these broken tests by adding explicit type annotations to our calls of `assert.Equal()`

### Reviewers

@dustinhiatt-wf @tannermiller-wf @beaulyddon-wf @stevenosborne-wf @tylertreat-wf

### CODE REVIEW

**Comment by tannermiller-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Comment by alexandercampbell-wf** [comment]
@dustinhiatt-wf are you okay with https://github.com/alexandercampbell-wf/go-datastructures/commit/6034e869e4d7795878f17314214fa1199ab17733 ?

**Comment by dustinhiatt-wf** [comment]
@alexandercampbell-wf, yeah, going to get back and make the corrections not noted in the paper as soon as possible :).

**Pull request merged**
