### PR TITLE
Check for race conditions and fail test build if they exist

### PR DESCRIPTION
**Pull request by jacobmoss-wf**
Verifying that Travis is functioning properly before mentioning reviewers.

### CODE REVIEW

**Comment by jacobmoss-wf** [comment]
@rosshendrickson-wf @ericolson-wf @alexandercampbell-wf @seanstrickland-wf @blakewilson-wf @matthinrichsen-wf @wesleybalvanz-wf

**Comment by wesleybalvanz-wf** [comment]
+1

**Comment by tylertreat-wf** [comment]
+1

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
