### PR TITLE
Fix #166

### LINKED ISSUE #166: Flatten() returns empty slice while reusing Set.
find a bug while using set, I'll make a PR late.

```go
set := set.New()
set.Add(1)
set.Add(2)
fmt.Println(set.Flatten()) // console: [1 2]
set.Dispose()
newSet := set.New(1)
fmt.Println(set.Flatten()) // console:[] expect:[1]
```

Reason:

While dispose an set, the `flattened` was just set to `set.flattened[:0]` in order to save the alloc for slice.

Every time calling updating function such like `Add(...)` or `Remove(...)` will reset `flattened` to nil.

And while calling `Flatten()`, if the `flattened` equals nil, will not recreate slice.

But while calling `New(...)` with init items, the `flattened` won't set to nil and next time to call `Flatten()` will got `flattened != nil` and return empty slice.

### PR DESCRIPTION
**Pull request by szyhf**
Ref #166, check len(items) .

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
Number of Findings: 0

**Comment by dustinhiatt-wf** [comment]
Thank you!  +1

**Comment by matthinrichsen-wf** [comment]
+1

**Comment by szyhf** [comment]
I'm not sure if other data struct has the same problem, may be you can check them ☺️ @dustinhiatt-wf @matthinrichsen-wf @aviary2-wf

**Pull request merged**
