### PR TITLE
Remove hasher pool from ctrie

### PR DESCRIPTION
**Pull request by tylertreat-wf**
The reduced memory allocations from using a hasher pool turns out to be
less efficient than just allocating a hasher per operation. On my
machine, this yields about a 14% speedup on Insert, 29% speedup on
Lookup, and 33% speedup on Remove. Also benchmarked sustained inserts.

Addresses #125.

@dustinhiatt-wf @alexandercampbell-wf @rosshendrickson-wf @stevenosborne-wf @tylerrinnan-wf @brianshannan-wf 

CC @newhook

### CODE REVIEW

**Comment by newhook** [comment]
+1 Thanks for that!

**Comment by brianshannan-wf** [comment]
+1

**Comment by stevenosborne-wf** [comment]
+1

**Comment by travisreed-wf** [comment]
rosie

**Pull request merged**
