### PR TITLE
Avl tree

### PR DESCRIPTION
**Pull request by dustinhiatt-wf**
CODE REVIEW

This is an immutable AVL tree.  Like clojure, this can serve as the foundation for many types of data structures.  I need to optimize for performance, introduce iterators, add predecessor/ancestor queries, etc.  I also need to add a more comprehensive testing suite.

Benchmarks:
BenchmarkImmutableInsert-8	 1000000	      1949 ns/op
BenchmarkImmutableGet-8	 3000000	       452 ns/op
BenchmarkImmutableBulkInsert-8	    3000	   9220036 ns/op
BenchmarkImmutableDelete-8	 1000000	      2477 ns/op
BenchmarkImmutableBulkDelete-8	   10000	  15048089 ns/op

I think there are some easy ways to get those numbers down, but I wanted to get this up as it's pretty dense.  I'll continue to iterate.

@tannermiller-wf @beaulyddon-wf @ericolson-wf @rosshendrickson-wf @alexandercampbell-wf @tylertreat-wf @stevenosborne-wf

### CODE REVIEW

**Comment by beaulyddon-wf** [comment]
Cool. +1

**Comment by tannermiller-wf** [comment]
+1 I'm so jealous that you get to pump out these cool data structures.

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by rosshendrickson-wf** [comment]
+1

**Pull request merged**
