### PR TITLE
RM-24272 Fix ctrie read-only snapshotting

### LINKED ISSUE #180: Ctrie read-only snapshot changes after creation
After:

- creating a Ctrie
- taking a read-only snapshot
- adding a key to the Ctrie

I'd expect the read-only snapshot to still be empty but it contains the added key.

### PR DESCRIPTION
**Pull request by tylertreat**
Fixes #180.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by fasaxc** [comment]
D'oh, I also made a fix: https://github.com/Workiva/go-datastructures/pull/182/files

**Comment by tylertreat** [comment]
Your fix looks better. Will close this PR.

**Comment by fasaxc** [comment]
Sorry, should have flagged that I was about to put up the PR!

**Pull request closed without merging**
