### PR TITLE
RM-30900 Handle duplicated entry in lNodes for the concurrent trie

### PR DESCRIPTION
**Pull request by stephane-martin**

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by dustinhiatt-wf** [comment]
@stephane-martin can you reproduce this in a test to confirm the fix?

**Comment by stephane-martin** [comment]
@dustincataldo-wf see https://github.com/Workiva/go-datastructures/issues/194

**Comment by dzyp** [comment]
@stephane-martin 

I added unit tests here: https://github.com/Workiva/go-datastructures/pull/198

**Pull request merged**
