### PR TITLE
RM-30900 Ctrie hash collisions

### PR DESCRIPTION
**Pull request by dzyp**
Builds on https://github.com/Workiva/go-datastructures/pull/195 but adds unit tests.

Addresses: https://github.com/Workiva/go-datastructures/issues/194

@stephane-martin
@dustinhiatt-wf 
@brianshannan-wf

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Comment by brianshannan-wf** [comment]
+1

**Pull request merged**
