### PR TITLE
remove race condition from test

### PR DESCRIPTION
**Pull request by Theodus**
This PR removes the race condition from the test of the dtrie and resolves #145

### CODE REVIEW

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
@Theodus Is this a race condition in the test or code?  Seems like an odd solution if there's a race condition in iterate.

**Comment by Theodus** [comment]
The race condition is that the loop wasn't broken after the channel received the 100'th element. Any values in transit would still be received, causing the loop to iterate and increment the counter.

**Comment by Theodus** [comment]
That's probably a better solution then removing the test entirely now that I think of it.

**Comment by alexandercampbell-wf** [comment]
:) +1

**Comment by dustinhiatt-wf** [comment]
+1

**Pull request merged**
