### PR TITLE
Create lockedSource for use by SkipList

### PR DESCRIPTION
**Pull request by nvanbenschoten**
Instead of having a static lock to provide thread safety for the
generator used by `SkipList`, the change models a `lockedSource` off of Go
stdlib's `globalRand` source. This is primarily a code refactor, but does
allow for locking at a smaller granularity.

There may be a better place to put this new type.

### CODE REVIEW

**Comment by tylertreat-wf** [comment]
lgtm

**Comment by alexandercampbell-wf** [comment]
+1

**Comment by dustinhiatt-wf** [comment]
+1

**Comment by alexandercampbell-wf** [comment]
Thanks for your contribution @nvanbenschoten!

**Pull request merged**
